# src/config.py

# Files
FILE_PATH = 'data/'
FILE_NAME = 'source_data.csv'
CSV_FILE = FILE_PATH + FILE_NAME
W2V_FILE_NAME = 'models/glove.6B.100d.txt.word2vec'

# General
MSEC = 1000
SECS_IN_MIN = 60
SEED = 42
KBYTE = 1024  # Corrected from 1042
COMMON_WORD_CNT = 20

# Label Sentiments
# -1 = Negative sentiment, 0 = neutral, 1 = positive
LABEL_NEGATIVE = 'Negative'
LABEL_NEUTRAL = 'Neutral'
LABEL_POSITIVE = 'Positive'
LABEL_NEGATIVE_INT = -1
LABEL_NEUTRAL_INT = 0
LABEL_POSITIVE_INT = 1
LABEL_SENTIMENT = {
    LABEL_NEGATIVE_INT: LABEL_NEGATIVE,
    LABEL_NEUTRAL_INT: LABEL_NEUTRAL,
    LABEL_POSITIVE_INT: LABEL_POSITIVE
}

# Data Splits
HALF_DATA_SPLIT = 0.5
TEMPORARY_DATA_SPLIT = 0.2
TRAINING_DATA_SPLIT = 0.8

# Models
FITTING_GAP_THRESH = 0.05
FITTING_SCORE_THRESH = 0.75

# Model: Base Parameters
BASE_ESTIMATOR_CNT = 300
BASE_DEPTH_MAX = 15
BASE_LEAF_MIN = 6
BASE_SPLIT_MIN = 30

# Model: Tuned Parameters
TUNED_ESTIMATOR_CNT = 500
TUNED_DEPTH_MAX = 7
TUNED_LEAF_MIN = 15
TUNED_SPLIT_MIN = 30

CV_FOLDS = 5
CV_RANDOM_SEARCH_CNT = 25
USE_ALL_PROCS = -1
SENTENCE_TRANSFER_MODEL = 'sentence-transformers/all-MiniLM-L6-v2'

# Vectors
GLOVE_VECTOR_SIZE = 100
W2V_EPOCH_CNT = 40
W2V_VECTOR_SIZE = 300
VEC_MAX_SIZE = 1000